### ISSUE TITLE
Uniform Image sizing for RSVP image display

### ISSUE THREAD

**Issue by nwayt001** [addisonbohannon/ILS#6]
RSVP images are currently presented in the native size of the image. Psychtoolbox Images need to be resized to a uniform size that would optimally be a input parameter.

**Comment by addisonbohannon** [comment]
I fixed the sizing issue so that they are all uniform sizes, however, i set the size manually. it would be nice to parameterize this.

**Comment by nwayt001** [comment]
Sizing issue is fixed. RSVP images are now all the same size with a parameter that is set inside of the rsvp_interface class.
